baseurl          = "/"
title           = "(title)"
languageCode    = "en-uk"
paginate        = "10"                                                                 # Number of posts per page
theme           = "coreui-hugo"

[Params]
    ghrepo      = "https://github.com/cx-candidates/master/"
